language: R
sudo: required
cache: packages

r:
- oldrel
- release
- devel

apt_packages:
- jags

r_packages:
- RcppArmadillo

r_check_args: "--no-vignettes --as-cran"
r_build_args: "--no-build-vignettes"
warnings_are_errors: false
